import type { Locale } from './types';
const english: Record<string,string> = {
  "收到陌生 NFT": "Unknown NFT",
  "突然出现在钱包里，要管吗？": "It appeared in my wallet. Now what?",
  "钱包公开地址，或 NFT 链接": "Public wallet address or NFT link",
  "粘贴 0x 开头的钱包地址，或单件 NFT 的链接": "Paste a wallet address starting with 0x, or an NFT item link",
  "先列出钱包中的 NFT，由你选出不认识的那一个。不用连接钱包。": "We’ll list your wallet’s NFTs so you can pick the unfamiliar one. No wallet connection needed.",
  "购买前查出处": "Before buying",
  "这个藏品，真是那个系列的吗？": "Does this item belong to that collection?",
  "NFT 商品链接": "NFT item link",
  "粘贴 OpenSea 或 Etherscan 的单件 NFT 链接": "Paste an individual NFT link from OpenSea or Etherscan",
  "我们从链接读取藏品信息，再独立核对官方出处。你不需要知道合约是什么。": "We’ll read the item details and check its official source. You don’t need to know about contracts.",
  "核验活动消息": "Check a message",
  "空投、白名单、奖励，是真的吗？": "Announcements, airdrops and rewards — true?",
  "收到的原始消息或链接": "The original message or link",
  "把群聊、私信或邮件里的活动内容粘贴到这里，保留其中的链接…": "Paste the message from your chat, DM or email, including its links…",
  "最好保留项目名字、活动时间和领取链接，方便逐条核对。": "Include the project name, dates and any links so we can check the details.",
  "找到官方出处": "Official source confirmed",
  "发现具体冲突 / 风险": "Conflict or risk found",
  "还不能确认": "Not enough evidence",
  "暂时无法完成，请稍后重试。": "Unable to complete this request. Please try again later.",
  "已复制核验摘要": "Summary copied",
  "复制失败，可以下载报告保存。": "Copy failed. You can download the report instead.",
  "跳到主要内容": "Skip to main content",
  "MintTrace 首页": "MintTrace home",
  "每一次核验，都有出处。": "Every check, backed by sources.",
  "核验记录": "History",
  "WEB3 来源核验助手": "WEB3 SOURCE CHECKER",
  "不确定，": "Not sure? ",
  "先查出处。": "Check the source.",
  "陌生的 NFT、想买的藏品、刚收到的活动消息。": "An unfamiliar NFT, a possible purchase, a message you just received.",
  "把你看到的交给我们，先查清，再决定。": "Bring what you saw. Get the evidence before you decide.",
  "发起核验": "Start a check",
  "选择场景": "Choose a check type",
  "只需要这一项": "That’s all we need",
  "有一项核验正在进行。": "A check is in progress. ",
  "查看进度": "View progress",
  "核验服务尚未配置好，请联系产品提供者。": "The checking service is not configured. Contact the product provider.",
  "Orbio Build Week 活动是真的吗？https://sellers.orbio.so/build": "Is Orbio Build Week real? https://sellers.orbio.so/build",
  "试填真实": "Try a real ",
  "活动": "announcement",
  "链接": " link",
  "正在读取…": "Reading…",
  "查看钱包里的 NFT": "Show wallet NFTs",
  "帮我查一下": "Check this",
  "哪一个是你不认识的？": "Which one don’t you recognize?",
  "已读取": "Loaded ",
  "件": " items",
  "· Ethereum · 数据来自 Blockscout。列表不是风险名单，也不保证最新到账排在前面。": " · Ethereum · Data from Blockscout. This is not a risk list and may not show the latest arrivals first.",
  "索引中没有找到 NFT。若钱包里确实有，可以直接粘贴该 NFT 的链接。": "No NFTs were found in the index. If your wallet shows one, paste its item link directly.",
  "发行者没有提供可读描述。": "The issuer did not provide a readable description.",
  "查这个 NFT": "Check this NFT",
  "读取中…": "Loading…",
  "继续加载 NFT": "Load more NFTs",
  "读取 · NFT 名称和描述来自发行者，尚未核实。": " · NFT names and descriptions come from their issuers and have not been verified.",
  "无需连接钱包，也不会要求签名。": "No wallet connection or signature needed.",
  "仅提交公开信息": "Public information only",
  "我们替你做的事": "HOW WE HELP",
  "你给线索，": "You bring the lead. ",
  "我们找依据。": "We find the evidence.",
  "读懂你看到的内容": "Understand the claim",
  "从商品链接、NFT 描述或消息里，提取需要核实的主张。": "Identify what needs checking in the item link, NFT description or message.",
  "找原始出处": "Follow the source",
  "从已收录的官方入口继续查公告，同时检查已知钓鱼记录。": "Read supplied pages, follow announcements and cross-check official sources.",
  "给一个有依据的下一步": "Make the next step clear",
  "说明哪里对得上、哪里有冲突，以及哪些暂时查不清。": "Explain what matches, what conflicts and what we still can’t establish.",
  "“有出处”不等于“签名安全”。": "A source match doesn’t make a signature safe.",
  "查不到时，我们会直接告诉你。": "If we can’t verify something, we’ll say so.",
  "现在能查什么？": "What can we check today?",
  "NFT 链接支持 OpenSea、Etherscan 的 Ethereum 主网单件资产；钱包读取 Ethereum ERC-721 / ERC-1155。官方入口覆盖 Arc、Loot、Nouns、Pudgy Penguins、Uniswap、Orbio。会跟进已发现的公告链接，并核对官网指向的社交账号。尚未接入全网搜索；其他项目可能只能确认页面内容，无法确认官方身份。": "NFT item links support Ethereum on OpenSea and Etherscan. Wallets support ERC-721 / ERC-1155. The official source directory covers Arc, Loot, Nouns, Pudgy Penguins, Uniswap and Orbio. We follow observed links and check social accounts against links on official sites. General web search is not connected; other projects may have content evidence without confirmed identity.",
  "已知钓鱼记录来自 Scam Sniffer 公共数据，约有 7 天延迟。网页可能无法读取，钱包索引可能延迟。本产品核对公开出处，不检查交易、授权或个人领取资格。": "Known phishing records come from Scam Sniffer’s public data, with about a 7-day delay. Pages may be inaccessible and wallet indexing can lag. We check public sources, not transactions, approvals or personal claim eligibility.",
  "提交的消息和 NFT 资料会发送给核验模型；钱包地址会用于查询 Blockscout。不要提交私钥、助记词或私人信息。当前预览仅供本机使用，核验记录保存在本机。": "Messages and NFT details are sent to the checking model; wallet addresses are queried through Blockscout. Do not submit private keys, recovery phrases or private information. This preview runs locally and stores checks on this device.",
  "最近查过的内容": "Recent checks",
  "当前设备的核验记录": "Checks saved on this device",
  "完成第一次核验后，记录会出现在这里。": "Your first completed check will appear here.",
  "正在核验": "Checking",
  "已停止": "Stopped",
  "未完成": "Incomplete",
  "再查一条": "Check something else",
  "早期研究记录": "Earlier research record",
  "这是改版前的合约比对记录，依赖当时由用户指定的参照，不能作为新版本的独立核验结果。": "This earlier contract comparison used a user-selected reference. It is not an independent source check from the current version.",
  "正在核对公开来源": "CHECKING PUBLIC SOURCES",
  "线索正在变成依据。": "Following the evidence.",
  "我们会按已有证据决定下一步。你可以留在这里，也可以稍后从记录继续查看。": "The evidence guides each next step. Stay here or return to this check from History.",
  "正在等待模型开始调查；尚未查询网页或链上资料。": "Waiting for the model to start. No webpages or on-chain records have been queried yet.",
  "停止本次核验": "Stop this check",
  "现在可以做的": "YOUR NEXT STEP",
  "当前官方来源目录没有找到对应项目，也尚未接入全网搜索。这份结果不能确认该项目的官方身份。": "The official source directory did not identify this project. General web search is not connected. Any page content found is separate from confirming the source’s identity.",
  "判断依据": "WHAT WE FOUND",
  "这次没有确认的部分": "What this check doesn’t establish",
  "只核对公开出处，不代表交易安全，也不替你决定是否购买。": "Public source checks do not establish transaction safety or decide whether you should buy.",
  "复制摘要": "Copy summary",
  "下载报告": "Download report",
  "重新核验": "Check again",
  "原始依据": "Source evidence",
  "条 · 可追溯": " records · traceable",
  "查看原始出处": "Open source",
  "待查网址（尚未确认身份）：": "URL examined (identity not confirmed): ",
  "查看调查经过 ·": "Investigation steps · ",
  "次行动": " actions",
  "这一步的来源暂时无法读取。": "This source could not be read.",
  "正在读取记录": "Loading this check",
  "返回首页": "Back to home",
  "有依据，再决定。": "Evidence before decisions.",
  "Orbio 推理": "Powered by Orbio",
  "开发测试版本": "Development preview"
};
export function translate(key: string, locale: Locale) { return locale === 'en' ? (english[key] || key) : key; }
